spring:
  profiles:
    include:
      - dev
      - security
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  devtools:
    livereload:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /crewchat